--1.ACTUALIZAR EL VALOR DE TODOS LOS PRODUCTO EN -20% 
UPDATE PRODUCTO 
SET PRECIO = PRECIO - (PRECIO * 0.20) 
--2.LISTAR LOS PRODUCTOS CON UN STOCK CRITICO MENOR O IGUAL A 5
SELECT * FROM PRODUCTO 
WHERE STOCK <= 5
--3.SIMULAR LA COMPRA DE 3 PRODUCTOS, SUBTOTAL, IVA ,MOSTRAR TOTAL DE COMPRA

UPDATE PRODUCTO SET STOCK = STOCK - 20 WHERE ID = 1;
UPDATE PRODUCTO SET STOCK = STOCK - 10 WHERE ID = 2;
UPDATE PRODUCTO SET STOCK = STOCK - 2 WHERE ID = 3;

SELECT SUM (DOR.CANTIDAD * DOR.PRECIO) AS SUBTOTAL
,(SUM (DOR.CANTIDAD * DOR.PRECIO) * 0.19) AS IVA 
,((SUM (DOR.CANTIDAD * DOR.PRECIO) * 0.19) +
SUM (DOR.CANTIDAD * DOR.PRECIO)) AS TOTAL  
FROM ORDEN AS O
INNER JOIN CLIENTE AS CL
ON CL.ID = O.ID_CLIENTE
INNER JOIN DETALLE_ORDEN AS DOR
ON DOR.ID = O.ID
WHERE O.ID_CLIENTE = 3
AND O.ID_ESTADO = 2;

--4.TOTAL DE VENTAS DURANTE EL MES DE DICIEMBRE 2022
SELECT COUNT(*) FROM ORDEN 
WHERE FECHA_ORDEN 
BETWEEN '2022/12/01' 
AND '2022/12/31';

--5.LISTAR EL USUARIO CON MAS COMPRAS DURANTE EL 2022
--EN CANTIDAD DE COMPRAS
SELECT CL.NOMBRE_CLIENTE,
SUM(DOR.CANTIDAD) AS CANTIDAD
FROM ORDEN AS O
INNER JOIN CLIENTE AS CL
ON CL.ID = O.ID_CLIENTE
INNER JOIN DETALLE_ORDEN AS DOR
ON DOR.ID = O.ID
GROUP BY CL.NOMBRE_CLIENTE
HAVING SUM(DOR.CANTIDAD) = 
(SELECT 
SUM(DOR.CANTIDAD) AS CANTIDAD
FROM ORDEN AS O
INNER JOIN CLIENTE AS CL
ON CL.ID = O.ID_CLIENTE
INNER JOIN DETALLE_ORDEN AS DOR
ON DOR.ID = O.ID
GROUP BY CL.NOMBRE_CLIENTE
ORDER BY CANTIDAD DESC
LIMIT 1);
